all: ext2_mkdir ext2_cp ext2_ln ext2_rm ext2_restore ext2_checker

ext2_mkdir:
	gcc -std=gnu99 -Wall -g $@.c -o $@ $^

ext2_cp:
	gcc -std=gnu99 -Wall -g $@.c -o $@ $^

ext2_ln:
	gcc -std=gnu99 -Wall -g $@.c -o $@ $^

ext2_rm:
	gcc -std=gnu99 -Wall -g $@.c -o $@ $^

ext2_restore:
	gcc -std=gnu99 -Wall -g $@.c -o $@ $^

ext2_checker:
	gcc -std=gnu99 -Wall -g $@.c -o $@ $^

clean:
	rm ext2_mkdir ext2_cp ext2_ln ext2_rm ext2_restore ext2_checker